# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Minghao Wang - PhD Student in Marketing"
title_separator          : "-"
name                     : &name "Minghao Wang"
description              : &description "PhD Student in Marketing at Michigan State University"
url                      : https://minghaowang-research.github.io
baseurl                  : "" 
repository               : "minghaowang-research/minghaowang-research.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Minghao Wang"
  pronouns         : "He/him/his"  
  bio              : "PhD Student in Marketing | Michigan State University"
  location         : "East Lansing, MI"
  employer         : "Eli Broad College of Business"
  uri              : 
  email            : "wangmi18@msu.edu"

  # Academic websites
  arxiv            : 
  googlescholar    : 
  impactstory      : 
  orcid            : 
  semantic         : 
  pubmed           : 
  researchgate     : 

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "minghaowang-research"
  kaggle           :   
  stackoverflow    :   

  # Social media
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "minghaomsuandcwru"
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/